# Python Basics

### Hello World!

In [2]:
#print() display output 
#in case the output is string must use " or '
print("Hello World!")

Hello World!


### Create and Assign Variables

In [3]:
#define variables with their values
x=5
print ("x =",x)
y=x
print ("y =",y )
z="string"
print(z)

x = 5
y = 5
string


### Data Types

In [4]:
#type() is a function that returns the type of the data
a=7
b=5.2
c="python"
d=True
print(a,type(a))
print(b,type(b))
print(c,type(c))
print(d,type(d))

7 <class 'int'>
5.2 <class 'float'>
python <class 'str'>
True <class 'bool'>


### Arithmatic Operations

In [5]:
num1=4
num2=2
print(num1 + num2)
print(num1 - num2)
print(num1 / num2)
print(num1 * num2)
print(num1 ** num2) #power

6
2
2.0
8
16


### Concatenation

In [6]:
word1="Hello"
word2="world"
print(word1 +" " + word2) # + = concatenate: add strings together
print(word1 +"\n" + word2) #"\n" = new line

Hello world
Hello
world


In [7]:
word1="Number"
number=2
word2=str(number) #str() convert integer type to string
print(word1 +" " + word2)

Number 2


In [9]:
#input() Ask the user for input and return it in string form
s=input("What is your name?")
print("Hello", s) 

What is your name?Hisham
Hello Hisham


### Wait

In [10]:
import time
#input() Ask the user for input and return it in string form
s=input("What is your name? ")
time.sleep(0.5)
print("Hello", s) 

What is your name? Hisham
Hello Hisham


In [22]:
# int() convert string type to integer 
numb1=int(input("Enter first number: "))
numb2=int(input("Enter second number: "))
time.sleep(1)
print(numb1,"+",numb2,"=",numb1 + numb2)

Enter first number: 5
Enter second number: 5
5 + 5 = 10


### If Condition

In [23]:
# if condition:
#    do something
# else: the condition is false
#    do something else
x=10
y=4
if x+y > 20:
    print (x+y,"> 20")
else:
    print(x+y,"< 20")

14 < 20


In [26]:
# elif = else if-> to check another condition
grade= 40
if grade >= 70:
    print("A")
elif grade < 70 and grade >= 60:
    print("B")
elif grade < 60 and grade >= 50:
    print("C")
else: 
    print("F")

F


In [27]:
x=True #True=1 ,false=0
if x == 1 : # == check if it's equal
    print("true")
else :
    print("false")

true


In [28]:
x=True 
if x != 1 : # != check if it's not equal
    print("true")
else :
    print("false")

false


### While loop

In [29]:
#while loop -> execute a set of statements as long as a condition is true (i<5)
i=0
while i<5:
    print(i)
    i=i+1

0
1
2
3
4


In [30]:
i=1
while i <= 5:
    print(i*"*")
    i+=1 #same as i=i+1

*
**
***
****
*****


In [31]:
#break used to Terminates the loop even if the while condition is true
x=10
while x >= 1:
    if x == 6:
        print("Terminates the loop")
        break
    print (x)
    x-=1

10
9
8
7
Terminates the loop


In [32]:
#continue used to Skip only the current iteration then continue in while loop
i = 10
while i > 1:
    i-=1
    if i == 6:
        print("Skip this iteration")
        continue
    print(i)

9
8
7
Skip this iteration
5
4
3
2
1


### For Loop

In [33]:
#for loop is used for iterating over a sequence like list
number=["one","two","three"] #list
for x in number:
    print(x)

one
two
three


In [34]:
numbers=[1,2,3,4,5,6]
for x in numbers:
    print(x+10)

11
12
13
14
15
16


In [35]:
for x in "Hello!":
    print(x)

H
e
l
l
o
!


In [36]:
#range(start,end,steps) function returns a sequence of numbers
#end in not included in the sequence
for i in range(4):
    print(i)

print ("loop2")
for i in range(1,5):
    print(i)

print ("loop3")
for i in range(1,10,2):
    print(i)

0
1
2
3
loop2
1
2
3
4
loop3
1
3
5
7
9


In [37]:
x1=[1,2]
x2=[1,2,3,4,5]
for i in x1: #nested loop: loop inside other loop
    for j in x2:
        print(i*j)

1
2
3
4
5
2
4
6
8
10


### List

In [40]:
# list -> collection of ordered and changeable elements
list1=[1,2,3,4,5]
#slicing [start:end:steps] returns new list from the existing list
print(list1[0])
print(list1[0:3])
print(list1[1:4:2])
print(list1[0:])
print(list1[::2])
print(list1[-1])#-1 = last element
print([list1]*2)
print(list1[0:3]*2)

1
[1, 2, 3]
[2, 4]
[1, 2, 3, 4, 5]
[1, 3, 5]
5
[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]
[1, 2, 3, 1, 2, 3]


In [45]:
#Multiply each item by value
print([x*2 for x in list1])

[2, 4, 6, 8, 10]


In [41]:
animals=["bird","cat","dog",1,2,3]
print (animals)
# append() is method that adds an element at the end of the list
animals.append("hamster")
print (animals)
#insert() is method that adds an element at the specified position
animals.insert(2,"turtle")
print (animals)
#remove() is method that removes the first item with the specified value
animals.remove("turtle")
print (animals)

['bird', 'cat', 'dog', 1, 2, 3]
['bird', 'cat', 'dog', 1, 2, 3, 'hamster']
['bird', 'cat', 'turtle', 'dog', 1, 2, 3, 'hamster']
['bird', 'cat', 'dog', 1, 2, 3, 'hamster']


### Tuple

In [42]:
tuple1=(1,2,'cat','dog')
print(tuple1,type(tuple1))

(1, 2, 'cat', 'dog') <class 'tuple'>


### Dictionary

In [43]:
#dictionary are used to store data values in key:value pairs 
dict={"name":"Ahmed",
      "age":20,
      "job":"student"}
print(dict)
print(dict["name"])
print(dict.keys())
print(dict.values())
print(dict.items())

{'name': 'Ahmed', 'age': 20, 'job': 'student'}
Ahmed
dict_keys(['name', 'age', 'job'])
dict_values(['Ahmed', 20, 'student'])
dict_items([('name', 'Ahmed'), ('age', 20), ('job', 'student')])


### Functions

In [46]:
# create custom function (arguments)
def fun1(x,y):
    total=x+y
    print(total)
fun1(10,20) #calling the function (parameters)

30


In [47]:
def numbers(num):
    list1=[]#create empty list
    for i in range(num):
        list1.append(i+1)
    return list1
numbers(5)

[1, 2, 3, 4, 5]

# NumPy library

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays

In [49]:
import numpy as np

In [50]:
#np.array creates an array
a=np.array([1,2,3])
print (a)
#a.ndim returns the dimension of the array
a.ndim

[1 2 3]


1

In [51]:
b=np.array([[1,2,3],[4,5,6]])
print (b)
print(b.ndim)
#b.shape returns the shape(number of rows, number of columns)
print(b.shape)
#b.dtype returns the data type of the elements
print(b.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int64


In [52]:
c=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],"\n")
print(c,"\n")
#print 7 ?
print(c[1,2],"\n")
print("Second row",c[-2,:],"\n")# : = all elements 
print("Last column",c[:,-1],"\n")
print("The middle 2 elements in row 2",c[1,1:3],"\n")
#set 3 = 20
c[0,2]=20
print("After change","\n",c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

7 

Second row [5 6 7 8] 

Last column [ 4  8 12] 

The middle 2 elements in row 2 [6 7] 

After change 
 [[ 1  2 20  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
#np.zeros(rows,columns) -> creates array filled with zeros
a=np.zeros((2,3))
print (a,"\n")
#np.ones(rows,columns) -> creates array filled with ones
b=np.ones((2,3))
print (b,"\n")
#np.full((rows,columns),number) -> creates array filled with specific number
c=np.full((2,3),4)
print (c,"\n")
#np.identity(square -> Rows = columns) -> creates array filled with ones at the diagonal
s=np.identity(3)
print(s,'\n','\n',s)

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[4 4 4]
 [4 4 4]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [59]:
#np.random.rand creates array of random numbers between 0 and 1 of specific size
d=np.random.rand(2,3)
print(d,"\n")
#np.random.randint creates array of random numbers between specified start and end integer numbers of specific size
e=np.random.randint(1,6,size=(2,3))#end is not included
print(e)

[[0.55586467 0.01617517 0.99124643]
 [0.57590248 0.00711971 0.21052483]] 

[[1 2 5]
 [4 2 4]]


In [60]:
x1=np.array([[1,2,3],[4,5,6]])
print(x1,"\n")
#Any change in x2 will be applied on x1
x2=x1
x2[0,1]=10
print("x1","\n",x1,"\n\n","x2","\n",x2)

[[1 2 3]
 [4 5 6]] 

x1 
 [[ 1 10  3]
 [ 4  5  6]] 

 x2 
 [[ 1 10  3]
 [ 4  5  6]]


In [63]:
y1=np.array([[1,2,3],[4,5,6]])
print(y1,"\n")
#copy() creates copy of y1 so any change in y2 will not be applied on y1
y2=y1.copy()
y2[0,1]=10
print("y1","\n",y1,"\n\n","y2","\n",y2)

[[1 2 3]
 [4 5 6]] 

y1 
 [[1 2 3]
 [4 5 6]] 

 y2 
 [[ 1 10  3]
 [ 4  5  6]]


In [64]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("arr","\n",arr,"\n")
print("arr+2","\n",arr+2,"\n")
print("arr-2","\n",arr-2,"\n")
print("arr*2","\n",arr*2,"\n")
print("arr/2","\n",arr/2,"\n")
print("arr**2","\n",arr**2,"\n")

arr 
 [[1 2 3 4]
 [5 6 7 8]] 

arr+2 
 [[ 3  4  5  6]
 [ 7  8  9 10]] 

arr-2 
 [[-1  0  1  2]
 [ 3  4  5  6]] 

arr*2 
 [[ 2  4  6  8]
 [10 12 14 16]] 

arr/2 
 [[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]] 

arr**2 
 [[ 1  4  9 16]
 [25 36 49 64]] 



In [65]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
#repeat(arr,number) flattening the array and repeat the array number of times
print(arr,"\n")

arr1= np.repeat(arr,2) 
print(arr1,"\n")

#if the axis is specified no flattening will happen
arr2 = np.repeat(arr,2,axis=0)# 0=row
print(arr2,"\n")

arr2 = np.repeat(arr,2,axis=1)# 1=column
print(arr2,"\n")

[[1 2 3 4]
 [5 6 7 8]] 

[1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8] 

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]] 

[[1 1 2 2 3 3 4 4]
 [5 5 6 6 7 7 8 8]] 



In [66]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
#np.vstack creates vertical stack of specific order ([order])
print("vertical","\n",np.vstack([a,b,a,b]),"\n")
#np.hstack creates horizontal stack of specific order ([order])
print("horizontal",np.hstack([b,a,b,a]))

vertical 
 [[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]] 

horizontal [5 6 7 8 1 2 3 4 5 6 7 8 1 2 3 4]


In [ ]:
k=np.array([[1,2,3,4],[5,6,7,8]])
k1=np.array([[9,10,11,12],[13,14,15,16]])
print(np.concatenate((k,k1),axis=0),"\n")
print(np.concatenate((k,k1),axis=1),"\n")
print(np.vstack([k,k1]),"\n")
print(np.hstack([k,k1]),"\n")

In [ ]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
a

In [ ]:
# 11,12,16,17
a[2:4,0:2]

In [ ]:
# diagonal
a[(0,1,2,3,4),(0,1,2,3,4)]

In [ ]:
#np.arange(start,end,number of steps) creates array , end is not included
x=np.arange(1,10,2)
print(x,"\n")
#np.linspace(start,end,number of samples) creates evenly spaced samples 
y=np.linspace(1,100,10)
print(y,"\n")
arr=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
#arr.reshape(Rows,columns) changes the array size (before 7*2=14, after must equal 14)
arr1=arr.reshape(7,2)
print(arr1,"\n")
print(arr1.flat[:],"\n")#flattening the array
#np.transpose(arr1)-> row=column and column=row
print(np.transpose(arr1),"\n")

In [ ]:
u=np.array([[1,2,3,4],[5,6,7,8]])
u1=np.append(u,[[9,10,11,12]],axis=0)
u2=np.append(u,[[5],[9]],axis=1)
print(u,"\n\n",u1,"\n\n",u2)

In [ ]:
r=k=np.array([[1,2,3,4],[5,6,7,8]])
r1=np.insert(r,0,[[11,12,13,14]],axis=0)
r2=np.insert(r,4,[10,11],axis=1)
print(r,"\n\n",r1,"\n\n",r2,"\n\n")
r3=np.delete(r,1,axis=1)
print(r3)

# Pandas library

In [67]:
import pandas as pd

In [68]:
#Series like list but with the presence of the index
s=pd.Series([1,2,3,4,'Ahmed',np.nan,9])
print(s,"\n")
data=np.array(['a','b','c','d'])
s1=pd.Series(data)
print(s1,"\n")
#Series from dictionary
data1={'a':1,'b':5,'c':8,'d':10}
s2=pd.Series(data1)
print(s2,"\n")

0        1
1        2
2        3
3        4
4    Ahmed
5      NaN
6        9
dtype: object 

0    a
1    b
2    c
3    d
dtype: object 

a     1
b     5
c     8
d    10
dtype: int64 



### Data Frame

In [69]:
#DataFrame is table with rows(index) and columns(columns)
df=pd.DataFrame(np.random.randint(1,7,size=(4,6)),index=['x','y','z','l'],columns=['a','b','c','d','e','f'])
print(df)

   a  b  c  d  e  f
x  2  6  1  2  4  6
y  2  3  6  2  1  4
z  6  6  4  6  2  4
l  3  6  6  4  6  4


In [73]:
df.head(4)

a  b  c  d  e  f
x  2  6  1  2  4  6
y  2  3  6  2  1  4
z  6  6  4  6  2  4
l  3  6  6  4  6  4

In [75]:
#describe() method is used for calculating some statistics of the data in the DataFrame
df.describe()

a     b         c         d         e    f
count  4.000000  4.00  4.000000  4.000000  4.000000  4.0
mean   3.250000  5.25  4.250000  3.500000  3.250000  4.5
std    1.892969  1.50  2.362908  1.914854  2.217356  1.0
min    2.000000  3.00  1.000000  2.000000  1.000000  4.0
25%    2.000000  5.25  3.250000  2.000000  1.750000  4.0
50%    2.500000  6.00  5.000000  3.000000  3.000000  4.0
75%    3.750000  6.00  6.000000  4.500000  4.500000  4.5
max    6.000000  6.00  6.000000  6.000000  6.000000  6.0

In [76]:
#Other syntax to create the DataFrame
df1=pd.DataFrame({'A':0.1,
                 'B':pd.Series([1,2,3,4]),
                 'C':np.array([3]*4),
                 'D':['A','B','C','D'],
                 'E':'Good'})
print(df1,"\n")
#df1.head(rows) print the first nth rows
print(df1.head(2),"\n")
#df1.tail(rows) print the last nth rows
print(df1.tail(2),"\n")
#df1.index print the indexes names in the dataFrame
print(df1.index,"\n")
#df1.columns print the columns names in the dataFrame
print(df1.columns,"\n")
#df1.values print the values of the dataFrame
print(df1.values,"\n")

     A  B  C  D     E
0  0.1  1  3  A  Good
1  0.1  2  3  B  Good
2  0.1  3  3  C  Good
3  0.1  4  3  D  Good 

     A  B  C  D     E
0  0.1  1  3  A  Good
1  0.1  2  3  B  Good 

     A  B  C  D     E
2  0.1  3  3  C  Good
3  0.1  4  3  D  Good 

RangeIndex(start=0, stop=4, step=1) 

Index(['A', 'B', 'C', 'D', 'E'], dtype='object') 

[[0.1 1 3 'A' 'Good']
 [0.1 2 3 'B' 'Good']
 [0.1 3 3 'C' 'Good']
 [0.1 4 3 'D' 'Good']] 



In [81]:
df2=pd.DataFrame(np.random.randint(1,6,size=(4,4)),index=['A','B','C','D'],columns=['one','two','three','four'])
df2

one  two  three  four
A    1    4      3     3
B    3    1      1     1
C    3    5      3     5
D    3    1      3     1

In [82]:
#df2.loc access the DataFrame based on the index or column name
print(df2.loc["B","three"],"\n")
print(df2.loc["C",:],"\n")
print(df2.loc[["C","D"],:],"\n")

1 

one      3
two      5
three    3
four     5
Name: C, dtype: int64 

   one  two  three  four
C    3    5      3     5
D    3    1      3     1 



In [83]:
#df2.iloc access the DataFrame based on the element index
print(df2.iloc[1,2],"\n")
print(df2.iloc[-2,],"\n")
print(df2.iloc[2:4,],"\n")

1 

one      3
two      5
three    3
four     5
Name: C, dtype: int64 

   one  two  three  four
C    3    5      3     5
D    3    1      3     1 



In [84]:
print(df2,"\n")
#df2.drop delete index or column with their values
a=df2.drop("three",axis=1)
print(a,"\n")
b=df2.drop("C",axis=0)
print(b,"\n")
c=df2.drop(["C","D"],axis=0)
print(c,"\n")

   one  two  three  four
A    1    4      3     3
B    3    1      1     1
C    3    5      3     5
D    3    1      3     1 

   one  two  four
A    1    4     3
B    3    1     1
C    3    5     5
D    3    1     1 

   one  two  three  four
A    1    4      3     3
B    3    1      1     1
D    3    1      3     1 

   one  two  three  four
A    1    4      3     3
B    3    1      1     1 



In [86]:
#df2.reindex rearranges the indexes or the columns according to specified order
# if there index or column is not exist it will be created with not a number(NaN) values
print(df2,"\n")
x=df2.reindex(["B","A","C","D","E"])
print("x =","\n",x,"\n","\n")
y=df2.reindex(["two","four","one","three","five"],axis=1)
print("y =","\n",y,"\n")
# sort_index() order the indexes
print("x after sorting","\n",x.sort_index())

   one  two  three  four
A    1    4      3     3
B    3    1      1     1
C    3    5      3     5
D    3    1      3     1 

x = 
    one  two  three  four
B  3.0  1.0    1.0   1.0
A  1.0  4.0    3.0   3.0
C  3.0  5.0    3.0   5.0
D  3.0  1.0    3.0   1.0
E  NaN  NaN    NaN   NaN 
 

y = 
    two  four  one  three  five
A    4     3    1      3   NaN
B    1     1    3      1   NaN
C    5     5    3      3   NaN
D    1     1    3      3   NaN 

x after sorting 
    one  two  three  four
A  1.0  4.0    3.0   3.0
B  3.0  1.0    1.0   1.0
C  3.0  5.0    3.0   5.0
D  3.0  1.0    3.0   1.0
E  NaN  NaN    NaN   NaN


In [87]:
print(y)
#y.isna() returns true if there value = NaN
print(y.isna())
#y.dropna() drop all values = Nan
print(y.dropna(axis=1))

   two  four  one  three  five
A    4     3    1      3   NaN
B    1     1    3      1   NaN
C    5     5    3      3   NaN
D    1     1    3      3   NaN
     two   four    one  three  five
A  False  False  False  False  True
B  False  False  False  False  True
C  False  False  False  False  True
D  False  False  False  False  True
   two  four  one  three
A    4     3    1      3
B    1     1    3      1
C    5     5    3      3
D    1     1    3      3


In [ ]:
x1=x.sort_index()
print(x1)
#x.max() print the maximum value default (0) in each columns
print(x1.max(axis=1))# Row = 1
#y.fillna() fill all values =Nan with the maximum
x.fillna(x1.max(),axis=0)

In [ ]:
select average(Fieldx), count(Fieldx),count(fieldy), count(distinct Fieldx), count(*) 
from Table_y;

1,1,2,1,2

In [ ]:
FieldX FieldY FieldZ
1       1      1
null    12     32
1       2      32

sum(nvl(fieldx,0))